# TODO: create docker-compose file

version: '3.7'
services:
  api:
    environment:
      COMPRESSION_SERVICE_HOST: http://localhost
      COMPRESSION_SERVICE_PORT: 8082
    build: .
    ports:
      - "8081:8081"
