data-service-config:
  host: "0.0.0.0"
  port: 8081
data-storage-config:
  mount-location: ${MOUNT_LOCATION}
compression-service:
  host: ${COMPRESSION_SERVICE_HOST}
  port: ${COMPRESSION_SERVICE_PORT}
  use-compression: true
